songs = [{'artist': 'Rocko Ministry',
  'title': '100000 Mystery [Radio Edit]',
  'bpm': 134.0,
  'year': 2006,
  'genre': 'Dance 2000s'},
 {'artist': 'Wes Montgomery',
  'title': "13 (Aka 'death March')",
  'bpm': 134.0,
  'year': 1996,
  'genre': 'Easy'},
 {'artist': 'Def Leppard',
  'title': '20th Century Boy',
  'bpm': 134.0,
  'year': 2006,
  'genre': 'Rock'},
 {'artist': 'Rush',
  'title': 'A Farewell to Kings',
  'bpm': 134.0,
  'year': 1990,
  'genre': 'Rock 1970s'},
 {'artist': 'Cheap Trick',
  'title': "Ain't That a Shame [Live]",
  'bpm': 134.0,
  'year': 1985,
  'genre': 'Rock 1980s'},
 {'artist': 'Meghan Trainor',
  'title': 'All About That Bass',
  'bpm': 134.0,
  'year': 2014,
  'genre': 'CHR'},
 {'artist': 'Buckcherry', 'title': 'All Night Long', 'bpm': 134.0, 'year': 2010, 'genre': 'Rock'},
 {'artist': 'Lasgo',
  'title': 'All Night Long [Mccullen & Ritter Remix]',
  'bpm': 134.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Cher', 'title': 'All or Nothing', 'bpm': 134.0, 'year': 1999, 'genre': 'TBD'},
 {'artist': 'Megadeth', 'title': 'Almost Honest', 'bpm': 134.0, 'year': 1997, 'genre': 'Fast Rock'},
 {'artist': 'Eleven & Seven',
  'title': '3AM Massive',
  'bpm': 135.0,
  'year': 1998,
  'genre': 'Dance 1990s'},
 {'artist': 'Britney Spears', 'title': '3', 'bpm': 135.0, 'year': 2009, 'genre': 'CHR'},
 {'artist': 'Robin Thicke',
  'title': '4 The Rest Of My Life [Clean Edit]',
  'bpm': 135.0,
  'year': 2013,
  'genre': 'Urban'},
 {'artist': 'The Killers',
  'title': 'A Dustland Fairytale',
  'bpm': 135.0,
  'year': 2009,
  'genre': 'Rock'},
 {'artist': 'Toby Keith',
  'title': "A Woman's Touch",
  'bpm': 135.0,
  'year': 1996,
  'genre': 'Country'},
 {'artist': 'Delerium Featuring Jael of Lunik',
  'title': 'After All [Svenson & Gielen Remix]',
  'bpm': 135.0,
  'year': 2003,
  'genre': 'Dance 2000s'},
 {'artist': 't.A.T.u.',
  'title': 'All About Us [Dave Aude Big Mixshow]',
  'bpm': 135.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Oxygen Featuring Andrea Britton',
  'title': 'Am I on Your Mind?',
  'bpm': 135.0,
  'year': 2003,
  'genre': 'Dance 2000s'},
 {'artist': 'Joee', 'title': 'Angel', 'bpm': 135.0, 'year': 1997, 'genre': 'Dance 1990s'},
 {'artist': 'Libra Presents Taylor',
  'title': 'Anomaly (Calling Your Name)',
  'bpm': 135.0,
  'year': 2000,
  'genre': 'TBD'},
 {'artist': '3T', 'title': '24/7', 'bpm': 136.0, 'year': 1996, 'genre': 'Slow Dance'},
 {'artist': 'Beyonce', 'title': '7/11', 'bpm': 136.0, 'year': 2015, 'genre': 'Urban'},
 {'artist': 'Blank & Jones Featuring Robert Smith',
  'title': 'A Forest [Club Mix]',
  'bpm': 136.0,
  'year': 2004,
  'genre': 'Dance 2000s'},
 {'artist': 'Blank & Jones Featuring Robert Smith',
  'title': 'A Forest [Short Cut]',
  'bpm': 136.0,
  'year': 2004,
  'genre': 'Dance 2000s'},
 {'artist': 'Baby Rockstar',
  'title': 'Across the Stars',
  'bpm': 136.0,
  'year': 2016,
  'genre': 'Kids'},
 {'artist': 'Sash!', 'title': 'Adelante', 'bpm': 136.0, 'year': 1999, 'genre': 'TBD'},
 {'artist': 'Lutricia McNeal',
  'title': "Ain't That Just the Way",
  'bpm': 136.0,
  'year': 1998,
  'genre': 'Dance 1990s'},
 {'artist': 'Cartoons', 'title': 'Aisy Waisy', 'bpm': 136.0, 'year': 1999, 'genre': 'TBD'},
 {'artist': 'Aluna',
  'title': 'All I Need Is Time [Sluslik Luna Mix]',
  'bpm': 136.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Aluna',
  'title': 'All I Need Is Time [Original Radio]',
  'bpm': 136.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Playahitty',
  'title': '1-2-3 (Train With Me)',
  'bpm': 137.0,
  'year': 1994,
  'genre': 'Dance 1990s'},
 {'artist': 'Kirsty Hawkshaw',
  'title': 'A Fine Day',
  'bpm': 137.0,
  'year': 2003,
  'genre': 'Dance 2000s'},
 {'artist': 'Kirsty Hawkshaw',
  'title': "A Fine Day [Mike Koglin 12'' Mix]",
  'bpm': 137.0,
  'year': 2003,
  'genre': 'Dance 2000s'},
 {'artist': 'Alicia Keys',
  'title': "A Woman's Worth",
  'bpm': 137.0,
  'year': 2002,
  'genre': 'Dance 2000s'},
 {'artist': 'Sister Hazel',
  'title': 'All for You',
  'bpm': 137.0,
  'year': 1997,
  'genre': 'Fast Rock'},
 {'artist': 'Kristina Maria Featuring JC Chasez',
  'title': 'Animal',
  'bpm': 137.0,
  'year': 2012,
  'genre': 'CHR'},
 {'artist': 'Martina McBride', 'title': 'Anyway', 'bpm': 137.0, 'year': 2007, 'genre': 'Country'},
 {'artist': 'Sherrie Lea',
  'title': 'Anyway [Seismic Crew Uplifting Club Mix]',
  'bpm': 137.0,
  'year': 2002,
  'genre': 'Dance 2000s'},
 {'artist': 'Raffi', 'title': 'Baby Beluga', 'bpm': 137.0, 'year': 1980, 'genre': 'Kids'},
 {'artist': 'Heart', 'title': 'Barracuda', 'bpm': 137.0, 'year': 1985, 'genre': 'Rock 1980s'},
 {'artist': 'Vengaboys', 'title': '48 Hours', 'bpm': 138.0, 'year': 2000, 'genre': 'Dance 2000s'},
 {'artist': 'Plummet',
  'title': '50 Ways to Leave Your Lover [MacQ Remix]',
  'bpm': 138.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Tommy Tutone',
  'title': '867-5309 - Jenny',
  'bpm': 138.0,
  'year': 1981,
  'genre': 'Dance 1980s'},
 {'artist': 'Yes', 'title': 'Abilene', 'bpm': 138.0, 'year': 1991, 'genre': 'Rock 1980s'},
 {'artist': 'Counting Crows',
  'title': 'Accidentally in Love',
  'bpm': 138.0,
  'year': 2004,
  'genre': 'Rock'},
 {'artist': 'DJ Tiesto',
  'title': 'Adagio for Strings [Phynn Remix]',
  'bpm': 138.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Saving Abel', 'title': 'Addicted', 'bpm': 138.0, 'year': 2008, 'genre': 'Rock'},
 {'artist': 'Blank & Jones',
  'title': 'After Love',
  'bpm': 138.0,
  'year': 2002,
  'genre': 'Dance 2000s'},
 {'artist': 'DJ Danny D',
  'title': 'Airbreak [Edit]',
  'bpm': 138.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Gigolo', 'title': 'Al Paradis', 'bpm': 138.0, 'year': 1999, 'genre': 'Dance 1990s'},
 {'artist': 'DJ Notorious',
  'title': 'Aa Dekhen Zara (Rocky)',
  'bpm': 139.0,
  'year': 2005,
  'genre': 'Special'},
 {'artist': 'Alice Deejay',
  'title': 'Back in My Life',
  'bpm': 139.0,
  'year': 2001,
  'genre': 'Dance 2000s'},
 {'artist': 'Toy-Box', 'title': 'Best Friend', 'bpm': 139.0, 'year': 1999, 'genre': 'TBD'},
 {'artist': 'The Beatles', 'title': 'Birthday', 'bpm': 139.0, 'year': 1968, 'genre': 'TBD'},
 {'artist': 'Milk Inc.', 'title': 'Blackout', 'bpm': 139.0, 'year': 2010, 'genre': 'Dance 2010s'},
 {'artist': 'DJ Tiesto Featuring BT',
  'title': 'Break My Fall [Airbase Remix]',
  'bpm': 139.0,
  'year': 2007,
  'genre': 'Dance 2000s'},
 {'artist': 'Neil Diamond',
  'title': "Brother Love's Traveling Salvation Show [Live]",
  'bpm': 139.0,
  'year': 2001,
  'genre': 'Easy'},
 {'artist': 'A-Town Players Featuring DJ Taz',
  'title': 'The Bump',
  'bpm': 139.0,
  'year': 1998,
  'genre': 'Dance 1990s'},
 {'artist': 'DJ Sammy',
  'title': "California Dreamin'",
  'bpm': 139.0,
  'year': 2003,
  'genre': 'Dance 2000s'},
 {'artist': 'The White Tie Affair',
  'title': 'Candle (Sick And Tired)',
  'bpm': 139.0,
  'year': 2009,
  'genre': 'CHR'},
 {'artist': 'Mike Will Made It Featuring Miley Cyrus & Wiz Khalifa',
  'title': '23 [Radio Edit]',
  'bpm': 140.0,
  'year': 2013,
  'genre': 'Urban'},
 {'artist': 'Vengaboys', 'title': '24 Hours', 'bpm': 140.0, 'year': 1999, 'genre': 'Dance 2000s'},
 {'artist': 'Steps', 'title': '5, 6, 7, 8', 'bpm': 140.0, 'year': 1998, 'genre': 'Dance 1990s'},
 {'artist': 'Train', 'title': '50 Ways To Say Goodbye', 'bpm': 140.0, 'year': 2012, 'genre': 'CHR'},
 {'artist': 'Ariana Grande',
  'title': '7 Rings [Clean Edit]',
  'bpm': 140.0,
  'year': 2019,
  'genre': 'CHR'},
 {'artist': 'Groove Coverage',
  'title': '7 Years And 50 Days [Casacada vs. Plasmatek Remix]',
  'bpm': 140.0,
  'year': 2004,
  'genre': 'Dance 2000s'},
 {'artist': 'CB Milton',
  'title': 'A Real Love',
  'bpm': 140.0,
  'year': 1996,
  'genre': 'Dance 1990s'},
 {'artist': 'Stone Sour', 'title': 'Absolute Zero', 'bpm': 140.0, 'year': 2012, 'genre': 'Rock'},
 {'artist': 'DJ Tiesto',
  'title': 'Adagio for Strings [Radio Edit]',
  'bpm': 140.0,
  'year': 2005,
  'genre': 'Dance'},
 {'artist': 'DJ Tiesto',
  'title': 'Adagio for Strings [Radio Edit]',
  'bpm': 140.0,
  'year': 2005,
  'genre': 'Dance 2000s'},
 {'artist': 'Liz Meyer',
  'title': 'All I Want [Club Mix Short]',
  'bpm': 141.0,
  'year': 2008,
  'genre': 'Dance 2000s'},
 {'artist': '2 Chainz Featuring Drake & Quavo',
  'title': 'Bigger Than You [Clean Edit]',
  'bpm': 141.0,
  'year': 2018,
  'genre': 'Urban'},
 {'artist': 'Doug Stone',
  'title': 'Born in the Dark',
  'bpm': 141.0,
  'year': 1995,
  'genre': 'Country'},
 {'artist': 'Travis Scott',
  'title': 'Butterfly Effect',
  'bpm': 141.0,
  'year': 2017,
  'genre': 'Urban'},
 {'artist': 'Hermitude Featuring Big K.R.I.T. & Mataya & Young Tapz',
  'title': 'The Buzz',
  'bpm': 141.0,
  'year': 2016,
  'genre': 'Dance 2010s'},
 {'artist': 'The Rolling Stones',
  'title': 'Continental Drift [Live]',
  'bpm': 141.0,
  'year': 1991,
  'genre': 'Rock 1970s'},
 {'artist': 'Brooklyn Bounce',
  'title': 'Crazy [Club Mix]',
  'bpm': 141.0,
  'year': 2004,
  'genre': 'Dance 2000s'},
 {'artist': '4 Strings',
  'title': 'Curious [Sam G Extended Mix]',
  'bpm': 141.0,
  'year': 2007,
  'genre': 'Dance 2000s'},
 {'artist': 'Lady Antebellum',
  'title': "Dancin' Away With My Heart",
  'bpm': 141.0,
  'year': 2012,
  'genre': 'Country'},
 {'artist': 'Savvas Paphiti', 'title': 'Dipsis', 'bpm': 141.0, 'year': 1994, 'genre': 'Easy'},
 {'artist': 'Super Why! Cast',
  'title': 'ABC, Sing with Me',
  'bpm': 142.0,
  'year': 2012,
  'genre': 'Kids'},
 {'artist': 'Anne-Marie',
  'title': 'Alarm [Marshmello Remix]',
  'bpm': 142.0,
  'year': 2017,
  'genre': 'Dance 2010s'},
 {'artist': 'Michael Buble',
  'title': 'All I Want For Christmas Is You',
  'bpm': 142.0,
  'year': 2011,
  'genre': 'XMAS'},
 {'artist': 'Kanye West Featuring Rihanna',
  'title': 'All Of The Lights',
  'bpm': 142.0,
  'year': 2011,
  'genre': 'Urban'},
 {'artist': 'The Strokes', 'title': 'All The Time', 'bpm': 142.0, 'year': 2013, 'genre': 'Rock'},
 {'artist': 'Marshmello', 'title': 'Alone', 'bpm': 142.0, 'year': 2016, 'genre': 'Dance 2010s'},
 {'artist': 'Paul van Dyk', 'title': 'Avenue', 'bpm': 142.0, 'year': 1999, 'genre': 'Dance 1990s'},
 {'artist': 'The Beatles',
  'title': 'Back in the Ussr',
  'bpm': 142.0,
  'year': 1969,
  'genre': 'Rock 1960s'},
 {'artist': 'Taylor Swift',
  'title': 'Back To December [Radio Edit]',
  'bpm': 142.0,
  'year': 2011,
  'genre': 'CHR'},
 {'artist': 'Balloon',
  'title': 'Bad & Sexy [Extended Mix]',
  'bpm': 142.0,
  'year': 2002,
  'genre': 'Dance 2000s'},
 {'artist': 'Barenaked Ladies',
  'title': 'Alcohol',
  'bpm': 143.0,
  'year': 1998,
  'genre': 'Rock 1990s'},
 {'artist': 'Bran Van 3000 Featuring Curtis Mayfield',
  'title': 'Astounded',
  'bpm': 143.0,
  'year': 2001,
  'genre': 'Rock 2000s'},
 {'artist': 'Young Jeezy Featuring Lil Wayne',
  'title': "Ballin'",
  'bpm': 143.0,
  'year': 2011,
  'genre': 'Urban'},
 {'artist': 'Janis Siegel',
  'title': 'Bei Mir Bist Du Schon',
  'bpm': 143.0,
  'year': 1993,
  'genre': 'Big Band'},
 {'artist': 'Megan Thee Stallion',
  'title': 'Big Ole Freak [Clean]',
  'bpm': 143.0,
  'year': 2019,
  'genre': 'Urban'},
 {'artist': 'JC Chasez', 'title': 'Build My World', 'bpm': 143.0, 'year': 2004, 'genre': 'CHR'},
 {'artist': 'KREAM', 'title': 'Deep End', 'bpm': 143.0, 'year': 2018, 'genre': 'Dance 2010s'},
 {'artist': 'Randy Travis',
  'title': 'Deeper Than the Holler',
  'bpm': 143.0,
  'year': 1988,
  'genre': 'Country'},
 {'artist': 'Gary Glitter',
  'title': 'Doing Alright With the Boys',
  'bpm': 143.0,
  'year': 1991,
  'genre': 'Rock 1990s'},
 {'artist': 'Collective Soul', 'title': 'Gel', 'bpm': 143.0, 'year': 1995, 'genre': 'Rock 1990s'},
 {'artist': 'Spice Girls',
  'title': '2 Become 1',
  'bpm': 144.0,
  'year': 1997,
  'genre': 'Slow Dance'},
 {'artist': 'Spice Girls', 'title': '2 Become 1', 'bpm': 144.0, 'year': 1997, 'genre': 'TBD'},
 {'artist': 'Royal Tusk', 'title': 'Aftermath', 'bpm': 144.0, 'year': 2018, 'genre': 'Rock'},
 {'artist': 'The Weepies',
  'title': 'All this Beauty',
  'bpm': 144.0,
  'year': 2008,
  'genre': 'Rock 2000s'},
 {'artist': 'Our Lady Peace',
  'title': 'All You Did Was Save My Life',
  'bpm': 144.0,
  'year': 2009,
  'genre': 'Rock'},
 {'artist': 'Aadesh Srivastava',
  'title': 'Allahu (Dev)',
  'bpm': 144.0,
  'year': 2005,
  'genre': 'Special'},
 {'artist': 'Jason Aldean',
  'title': "Any Ol' Barstool",
  'bpm': 144.0,
  'year': 2017,
  'genre': 'Country'},
 {'artist': 'Roxette', 'title': 'Anyone', 'bpm': 144.0, 'year': 1999, 'genre': 'TBD'},
 {'artist': 'Gloria Estefan',
  'title': 'Anything for You',
  'bpm': 144.0,
  'year': 1992,
  'genre': 'Rock 1980s'},
 {'artist': 'The Beach Boys',
  'title': 'Be True to Your School',
  'bpm': 144.0,
  'year': 1963,
  'genre': 'Rock 1960s'},
 {'artist': 'David Guetta Featuring Justin Bieber',
  'title': '2U',
  'bpm': 145.0,
  'year': 2017,
  'genre': 'Dance'},
 {'artist': 'DJ Drama', 'title': '4 What', 'bpm': 145.0, 'year': 2013, 'genre': 'Urban'},
 {'artist': 'Rick Ross Featuring Lil Wayne',
  'title': '9 Piece',
  'bpm': 145.0,
  'year': 2011,
  'genre': 'Urban'},
 {'artist': 'Basshunter',
  'title': 'All I Ever Wanted',
  'bpm': 145.0,
  'year': 2008,
  'genre': 'Dance 2000s'},
 {'artist': 'Jeezy Featuring Bankroll Fresh',
  'title': 'All There [Edited]',
  'bpm': 145.0,
  'year': 2016,
  'genre': 'Urban'},
 {'artist': 'Kim Sozzi',
  'title': 'Alone [Johnny Budz Radio Mix]',
  'bpm': 145.0,
  'year': 2006,
  'genre': 'Dance 2000s'},
 {'artist': 'Jordin Sparks', 'title': 'Battlefield', 'bpm': 145.0, 'year': 2009, 'genre': 'CHR'},
 {'artist': 'Gipp Featuring Eric Benet',
  'title': 'Beautiful Lover',
  'bpm': 145.0,
  'year': 2015,
  'genre': 'Urban'},
 {'artist': 'Post Malone',
  'title': 'Better Now [Clean Single Edit]',
  'bpm': 145.0,
  'year': 2018,
  'genre': 'CHR'},
 {'artist': 'Purple Ribbon Allstars',
  'title': 'Body Rock',
  'bpm': 145.0,
  'year': 2006,
  'genre': 'Urban'},
 {'artist': 'Pop Evil', 'title': '100 In A 55', 'bpm': 146.0, 'year': 2009, 'genre': 'Rock'},
 {'artist': 'The Veronicas', 'title': '4Ever', 'bpm': 146.0, 'year': 2005, 'genre': 'CHR'},
 {'artist': '21 Savage Featuring J. Cole',
  'title': 'a lot [Clean Edit]',
  'bpm': 146.0,
  'year': 2019,
  'genre': 'Urban'},
 {'artist': 'Kim Mitchell',
  'title': "Ain't Life Amazing",
  'bpm': 146.0,
  'year': 2007,
  'genre': 'Rock'},
 {'artist': 'OneRepublic',
  'title': 'All The Right Moves',
  'bpm': 146.0,
  'year': 2010,
  'genre': 'CHR'},
 {'artist': 'George Canyon',
  'title': "Betty's Buns",
  'bpm': 146.0,
  'year': 2009,
  'genre': 'Country'},
 {'artist': 'Wintersleep', 'title': 'Black Camera', 'bpm': 146.0, 'year': 2010, 'genre': 'Rock'},
 {'artist': 'Mario Featuring Gucci Mane & Sean Garrett',
  'title': 'Break Up',
  'bpm': 146.0,
  'year': 2009,
  'genre': 'Urban'},
 {'artist': 'D.R.A.M. Featuring Lil Yachty',
  'title': 'Broccoli [Clean]',
  'bpm': 146.0,
  'year': 2016,
  'genre': 'Urban'},
 {'artist': 'Tim Hicks',
  'title': 'Buzz, Buzz Buzzing',
  'bpm': 146.0,
  'year': 2013,
  'genre': 'Country'},
 {'artist': 'Flyleaf', 'title': 'All Around Me', 'bpm': 147.0, 'year': 2008, 'genre': 'CHR'},
 {'artist': 'Glee Cast',
  'title': 'All I Want For Christmas Is You',
  'bpm': 147.0,
  'year': 2011,
  'genre': 'Easy'},
 {'artist': 'Elvis Presley',
  'title': 'All Shook Up',
  'bpm': 147.0,
  'year': 1957,
  'genre': 'Rock 1950s'},
 {'artist': 'The Dave Clark Five',
  'title': 'Any Way You Want It',
  'bpm': 147.0,
  'year': 1965,
  'genre': 'Rock 1960s'},
 {'artist': 'Mike Posner Featuring Lil Wayne',
  'title': 'Bow Chicka Wow Wow [Clean]',
  'bpm': 147.0,
  'year': 2011,
  'genre': 'CHR'},
 {'artist': 'The Lonely Island featuring Too Short',
  'title': 'The Compliments',
  'bpm': 147.0,
  'year': 2013,
  'genre': 'Rock 2010s'},
 {'artist': 'Stereophonics',
  'title': 'Dakota (You Made Me Feel Like the One)',
  'bpm': 147.0,
  'year': 2005,
  'genre': 'Rock'},
 {'artist': 'Madonna',
  'title': "Devil Wouldn't Recognize You",
  'bpm': 147.0,
  'year': 2008,
  'genre': 'Dance 2000s'},
 {'artist': 'Tim McGraw',
  'title': 'Drugs or Jesus',
  'bpm': 147.0,
  'year': 2005,
  'genre': 'Country'},
 {'artist': 'Barenaked Ladies',
  'title': 'Duct Tape Heart',
  'bpm': 147.0,
  'year': 2015,
  'genre': 'Rock 2010s'},
 {'artist': 'Sarah Brightman',
  'title': 'A Whiter Shade of Pale',
  'bpm': 148.0,
  'year': 2000,
  'genre': 'Slow'},
 {'artist': 'The Beatles',
  'title': 'Across the Universe',
  'bpm': 148.0,
  'year': 1969,
  'genre': 'Rock 1960s'},
 {'artist': 'Linda Ronstadt & Aaron Neville',
  'title': 'All My Life',
  'bpm': 148.0,
  'year': 1990,
  'genre': 'Slow'},
 {'artist': 'Kelly Clarkson', 'title': 'Already Gone', 'bpm': 148.0, 'year': 2009, 'genre': 'CHR'},
 {'artist': 'Neon Trees', 'title': 'Animal', 'bpm': 148.0, 'year': 2010, 'genre': 'Rock'},
 {'artist': 'Maxwell', 'title': 'Bad Habits', 'bpm': 148.0, 'year': 2009, 'genre': 'Urban'},
 {'artist': 'Mandalay',
  'title': "Beautiful [Canny 12'' Mix]",
  'bpm': 148.0,
  'year': 1998,
  'genre': 'Dance 2000s'},
 {'artist': 'Young Money Featuring Lloyd Polite',
  'title': 'Bedrock',
  'bpm': 148.0,
  'year': 2010,
  'genre': 'Urban'},
 {'artist': 'Young Money Featuring Lloyd Polite',
  'title': 'Bedrock',
  'bpm': 148.0,
  'year': 2010,
  'genre': 'Urban'},
 {'artist': 'Carrie Underwood',
  'title': 'Before He Cheats',
  'bpm': 148.0,
  'year': 2006,
  'genre': 'Country'},
 {'artist': 'Howard Jones',
  'title': 'Always Asking Questions',
  'bpm': 149.0,
  'year': 1984,
  'genre': 'Rock 1980s'},
 {'artist': 'Tracy Chapman',
  'title': 'Baby Can I Hold You',
  'bpm': 149.0,
  'year': 1988,
  'genre': 'Easy'},
 {'artist': 'Louis Tomlinson Featuring Bebe Rexha & Digital Farm Animals',
  'title': 'Back To You [Digital Farm Animals Remix]',
  'bpm': 149.0,
  'year': 2017,
  'genre': 'Dance 2010s'},
 {'artist': 'Slash Featuring Myles Kennedy And The Conspirators',
  'title': 'Bent To Fly',
  'bpm': 149.0,
  'year': 2015,
  'genre': 'Rock'},
 {'artist': 'D4L',
  'title': "Betcha Can't Do It Like Me",
  'bpm': 149.0,
  'year': 2006,
  'genre': 'Urban'},
 {'artist': 'Flight Of The Conchords',
  'title': 'Carol Brown',
  'bpm': 149.0,
  'year': 2009,
  'genre': 'Rock 2000s'},
 {'artist': 'Florida Georgia Line Featuring Nelly',
  'title': 'Cruise [Remix]',
  'bpm': 149.0,
  'year': 2013,
  'genre': 'CHR'},
 {'artist': 'We Are Toonz',
  'title': 'Drop That #NaeNae',
  'bpm': 149.0,
  'year': 2014,
  'genre': 'Urban'},
 {'artist': 'Calboy', 'title': 'Envy Me [Clean]', 'bpm': 149.0, 'year': 2019, 'genre': 'Urban'},
 {'artist': 'Jose Feliciano',
  'title': 'Feliz Navidad',
  'bpm': 149.0,
  'year': 1970,
  'genre': 'XMAS'}]
